#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate Audio Studio configuration files from Kconfig."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


def load_kconfiglib():
    try:
        import kconfiglib  # type: ignore
    except ImportError:
        print("error: Python package 'kconfiglib' is required", file=sys.stderr)
        print("install it with: pip install kconfiglib", file=sys.stderr)
        raise SystemExit(2)
    return kconfiglib


def write_header(kconf, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write("/* Generated by scripts/kconfig/genconfig.py. */\n")
        f.write("#pragma once\n\n")
        for sym in kconf.unique_defined_syms:
            name = sym.name
            value = sym.str_value
            if not name or value in ("", "n"):
                continue
            if value == "y":
                f.write(f"#define CONFIG_{name} 1\n")
            elif sym.type == kconf.STRING:
                escaped = value.replace('\\', '\\\\').replace('"', '\\"')
                f.write(f"#define CONFIG_{name} \"{escaped}\"\n")
            else:
                f.write(f"#define CONFIG_{name} {value}\n")


def write_cmake(kconf, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write("# Generated by scripts/kconfig/genconfig.py.\n")
        for sym in kconf.unique_defined_syms:
            name = sym.name
            value = sym.str_value
            if not name or value == "":
                continue
            escaped = value.replace('\\', '\\\\').replace('"', '\\"')
            f.write(f"set(CONFIG_{name} \"{escaped}\")\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--kconfig", required=True)
    parser.add_argument("--config", required=True)
    parser.add_argument("--dotconfig", required=True)
    parser.add_argument("--header", required=True)
    parser.add_argument("--cmake", required=True)
    args = parser.parse_args()

    kconfiglib = load_kconfiglib()
    kconf = kconfiglib.Kconfig(args.kconfig)
    kconf.load_config(args.config, replace=True)
    dotconfig = Path(args.dotconfig)
    dotconfig.parent.mkdir(parents=True, exist_ok=True)
    kconf.write_config(str(dotconfig))
    write_header(kconf, Path(args.header))
    write_cmake(kconf, Path(args.cmake))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
