#ifndef AUDIO_STUDIO_SOF_LOGGER_UUID_REGISTRY_H_
#define AUDIO_STUDIO_SOF_LOGGER_UUID_REGISTRY_H_

/*
 * SOF's logger convert path needs sof/lib/uuid.h for struct layouts only.
 * Registry macro values are generated by firmware builds and are not used by
 * the host-side decoder path embedded in Audio Studio.
 */

#endif
